from pathlib import Path

import pytest
from pydantic import ValidationError
from zero_3rdparty.file_utils import ensure_parents_write_text

from pkg_ext._internal.config import (
    ExposeMode,
    GroupConfig,
    ProjectConfig,
    load_project_config,
    validate_group_dependencies,
)
from pkg_ext._internal.models import PublicGroup, PublicGroups
from pkg_ext._internal.settings import pkg_settings

example_pyproject_toml = """\
[tool.pkg-ext]
tag_prefix = "a"
after_file_write_hooks = [
  "just quick",
]
"""


def test_load_project_config(tmp_path):
    file = tmp_path / "pyproject.toml"
    file.write_text(example_pyproject_toml)
    config = load_project_config(tmp_path)
    assert config.after_file_write_hooks


pyproject_with_groups = """\
[tool.pkg-ext]

[tool.pkg-ext.groups.datez]
docstring = "Date utilities"

[tool.pkg-ext.groups.filez]
dependencies = ["datez"]
docs_exclude = ["_internal_helper"]
"""


def test_load_project_config_with_groups(tmp_path):
    file = tmp_path / "pyproject.toml"
    file.write_text(pyproject_with_groups)
    config = load_project_config(tmp_path)

    assert len(config.groups) == 2

    datez = config.groups["datez"]
    assert datez.docstring == "Date utilities"
    assert datez.dependencies == []

    filez = config.groups["filez"]
    assert filez.dependencies == ["datez"]
    assert filez.docs_exclude == ["_internal_helper"]


def test_group_config_defaults():
    cfg = GroupConfig()
    assert cfg.dependencies == []
    assert cfg.docs_exclude == []
    assert cfg.docstring == ""
    assert cfg.examples_include == []


pyproject_valid_deps = """\
[tool.pkg-ext]
[tool.pkg-ext.groups.core]
[tool.pkg-ext.groups.utils]
dependencies = ["core", "__ROOT__"]
"""


def test_valid_dependencies(tmp_path):
    (tmp_path / "pyproject.toml").write_text(pyproject_valid_deps)
    config = load_project_config(tmp_path)
    assert config.groups["utils"].dependencies == ["core", "__ROOT__"]


pyproject_invalid_dep = """\
[tool.pkg-ext]
[tool.pkg-ext.groups.utils]
dependencies = ["nonexistent"]
"""


def test_invalid_dependency_raises(tmp_path):
    (tmp_path / "pyproject.toml").write_text(pyproject_invalid_dep)
    with pytest.raises(ValueError, match="invalid dependency 'nonexistent'"):
        load_project_config(tmp_path)


pyproject_circular = """\
[tool.pkg-ext]
[tool.pkg-ext.groups.a]
dependencies = ["b"]
[tool.pkg-ext.groups.b]
dependencies = ["a"]
"""


def test_circular_dependency_raises(tmp_path):
    (tmp_path / "pyproject.toml").write_text(pyproject_circular)
    with pytest.raises(ValueError, match="Circular dependency"):
        load_project_config(tmp_path)


def test_validate_group_dependencies_against_runtime():
    config = ProjectConfig(groups={"core": GroupConfig(), "utils": GroupConfig(dependencies=["core"])})
    runtime = PublicGroups(groups=[PublicGroup(name="__ROOT__")])
    with pytest.raises(ValueError, match="unknown runtime group 'core'"):
        validate_group_dependencies(config, runtime)


def test_merge_config_and_write(tmp_path):
    config = ProjectConfig(
        groups={
            "datez": GroupConfig(docstring="Date utils"),
            "filez": GroupConfig(dependencies=["datez"]),
        }
    )
    output_path = tmp_path / ".groups.yaml"
    groups = PublicGroups(storage_path=output_path)
    groups.add_module("datez", "datez_module")
    groups.merge_config(config)
    groups.write()

    datez = groups.name_to_group["datez"]
    assert datez.docstring == "Date utils"
    assert "datez_module" in datez.owned_modules

    filez = groups.name_to_group["filez"]
    assert filez.dependencies == ["datez"]

    content = output_path.read_text()
    assert "docstring: Date utils" in content
    assert "dependencies:" in content
    assert "# generated by pkg-ext from pyproject.toml" in content


def test_expose_mode_defaults_to_prompt():
    assert ProjectConfig().expose_mode == ExposeMode.prompt
    assert load_project_config(Path("/missing/pyproject.toml")).expose_mode == ExposeMode.prompt


@pytest.mark.parametrize("value", ["prompt", "cli_only", "opt_in"])
def test_load_expose_mode_from_pyproject(tmp_path: Path, value: str):
    ensure_parents_write_text(
        tmp_path / "pyproject.toml",
        f'[tool.pkg-ext]\nexpose_mode = "{value}"\n',
    )
    assert load_project_config(tmp_path).expose_mode == ExposeMode(value)


def test_invalid_expose_mode_rejected():
    with pytest.raises(ValidationError):
        ProjectConfig(expose_mode="always_public")


def test_pkg_settings_copies_expose_mode(tmp_path: Path):
    ensure_parents_write_text(tmp_path / "pyproject.toml", '[tool.pkg-ext]\nexpose_mode = "cli_only"\n')
    pkg_dir = tmp_path / "pkg"
    ensure_parents_write_text(pkg_dir / "__init__.py", "")
    settings = pkg_settings(tmp_path, "pkg", skip_open_in_editor=True)
    assert settings.expose_mode == ExposeMode.cli_only
