# Generated by pkg-ext
from pkg_ext._internal.cli.example_cmds import check_examples as _check_examples
from pkg_ext._internal.cli.example_cmds import gen_example_prompt as _gen_example_prompt

check_examples = _check_examples
gen_example_prompt = _gen_example_prompt
